version: '3'

services:
  
  nginx:
  	build: .docker/nginx
  	container_name: nginx-modsecurity
  	restart: always
  	tty: true
  	ports:
  	  - "8000:80"
  	volumes:
  	  - .docker/app/:/var/www
  	networks:
  	  - ahs-net




networks:
  ahs-net:
    driver: bridge
