version: '3'

services:

  app:
  	build:
  	  context: .docker/app
  	  dockerfile: api.Dockerfile
  	container_name: app
  	tty: true
  	restart: always
  	volumes:
  	  - .docker/app/:/var/www
  	networks:
  	  - ahs-net
  	depends_on:
  	  - nginx
  	  - mysql
  	  - redis
  
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    tty: true
    expose:
      - 6379
    networks:
      - ahs-net
    depends_on:
      - nginx

  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    tty: true
    ports:
      - "3307:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - ahs-net

  nginx:
  	build: .docker/nginx
  	container_name: nginx-waf
  	restart: always
  	tty: true
  	ports:
  	  - "8000:80"
  	volumes:
  	  - .docker/app/:/var/www
  	networks:
  	  - ahs-net

networks:
  ahs-net:
    driver: bridge